# -*- coding: utf-8 -*-

"""

daisk_cache.py: decorator for diskcache, for async functions

edward | 2024-10-03


EXAMPLES

@disk_cache(cache_dir=r"/tmp/cache/a")
async def my_func(a : int, b: int, c: int):
    return a + b + c

       
# clear cache
my_func.clear()

"""
from hashlib import md5
from inspect import signature
from io import BytesIO
from json import dumps
from typing import List, Union, Tuple, Any, Dict

from diskcache import Cache



# logging
from serentec.utils.logger import logger_dl
module_logger = logger_dl.getChild("adisk_cache")

_diskcache: Dict[str, Cache] = {}

def adisk_cache(cache_dir : str = r"/tmp/disk_cache", return_cache_used_flag : bool = False):
    """

    :param cache_dir: location of the cache directory

    :param return_cache_used_flag: if True, returns a 2-tuple:
        - value, either newly generated by the wrapped function or the cached value
        - boolean with value True if the value was retrieved from cache

    Returns either the value (cached or newly generated) or a 2-tuple (see return_cache_used_flag)
            
    """

    module_logger.info(f"Created async disk cache | {cache_dir}")
            
    def disk_cache_decorator(func):
        
        # NOTE: explicitly ignore self and cls arguments that are 99.999% the class instance passed in the (self, ) call, which should not be taken into account for caching purposes
        _is_method = next(iter(signature(func).parameters), None) in ("self", "cls")

        async def wrapper(*args, **kwargs) -> Union[Any, Tuple[Any, bool]]:
            if cache_dir not in _diskcache:
                _diskcache[cache_dir] = Cache(cache_dir)
                module_logger.debug(f"disk_cache created | {cache_dir}")

            # compute hash of all arguments and kwargs
            # BACKLOG: if not, then cacheing is not possible => call function
            cache_args = args[1:] if _is_method else args
            args_str = dumps({"args" : cache_args, "kwargs" : kwargs})
            hash = md5(args_str.encode("UTF-8")).hexdigest()

            if hash in _diskcache[cache_dir]:
                cached_result = _diskcache[cache_dir].get(hash)
                if return_cache_used_flag:
                    return cached_result, True
                else:
                    return cached_result
            else:
                # cache miss => call function
                result = await func(*args, **kwargs)

                # write value to cache
                if isinstance(result, bytes):
                    _diskcache[cache_dir].set(hash, BytesIO(result), read=True)
                else:
                    _diskcache[cache_dir].set(hash, result)

                if return_cache_used_flag:
                    return result, False
                else:
                    return result
            
        
        
        # create a function that allows calling my_func.clear()
        def clear():
            """
            clear the cache
            """
            if cache_dir not in _diskcache:
                _diskcache[cache_dir] = Cache(cache_dir)
            
            _diskcache[cache_dir].clear()
            module_logger.debug(f"disk_cache cleared | {cache_dir}")

        wrapper.clear = clear
            
        
        return wrapper
    return disk_cache_decorator