# -*- coding: utf-8 -*-

"""

disk_cache.py: decorator for diskcache

NOTES
- careful! values are automatically ejected from the cache if size limit is exceeded; set a sufficiently high limit for size_limit_gb

edward | 2025-04-30

INSTALL
pip3 install diskcache #==5.6.3

EXAMPLES

@disk_cache(cache_dir=r"/tmp/cache/a")
def my_func(a : int, b: int, c: int):
    return a + b + c

       
# clear cache
my_func.clear()

"""
from hashlib import md5
from io import BytesIO
from json import dumps
from time import perf_counter
from threading import Lock
from typing import List, Union, Tuple, Any

from diskcache import Cache



# logging
from serentec.utils.logger import logger_dl
module_logger = logger_dl.getChild("disk_cache")

# NOTE: we need one disk cache per cache dir, because a same application may be using multiple caches for different objects
# see /Users/gaeree/SerenTec2/serentec/providers/protected/sdmx1/sdmx1_base.py
# @disk_cache(cache_dir=r"/tmp/cache/sdmx1/dataflows", size_limit_gb=10, debug=True)
# @disk_cache(cache_dir=r"/tmp/cache/sdmx1/datastructure", size_limit_gb=10, debug=True)
# ...
_diskcache = {}

# NOTE: make thread safe
_diskcache_lock = Lock()

def disk_cache(cache_dir : str = r"/tmp/disk_cache"
               , return_cache_used_flag : bool = False
               , size_limit_gb : int = 1  # 1gb
               , debug : bool = False
               ):
    """

    :param size_limit_gb: size limit in gb; keys get automatically evicted 

    Returns a 2-tuple:
        - value, either newly generated by the wrapped function or the cached value
        - boolean with value True if the value was retrieved from cache
            
    """
            
    def disk_cache_decorator(func):
        
        def wrapper(*all_args, **kwargs) -> Union[Any, Tuple[Any, bool]]:
            global _diskcache
            
            # ensure two threads don't try to create a cache at the same time
            with _diskcache_lock:
                if cache_dir not in _diskcache:
                    _diskcache[cache_dir] = Cache(cache_dir, size_limit=size_limit_gb * (2**30))

                    if debug:
                        module_logger.debug(f"disk_cache ready | {cache_dir} | size limit : {size_limit_gb} gb")

            # detect method call, i.e. when the first argument is 'self'; we don't want to serialise the class...
            # in such cases, first arg is an instance that has this function as attribute
            args = all_args
            if all_args and hasattr(all_args[0], func.__name__):
                args = all_args[1:]  # skip self

            # compute hash of all arguments and kwargs
            # BACKLOG: if not, then cacheing is not possible => call function
            args_str = dumps({"args" : args, "kwargs" : kwargs})
            hash = md5(args_str.encode("UTF-8")).hexdigest()

            if hash in _diskcache[cache_dir]:
                # cache hit
                if debug:
                    t0 = perf_counter()
                    module_logger.debug(f"Cache hit | hash : {hash} | args : {args} | kwargs : {kwargs} | reading from cache...")

                cached_result = _diskcache[cache_dir].get(hash)
                
                if debug:
                    t1 = perf_counter()
                    elapsed_milliseconds = 1000.0 * (t1 - t0)
                    module_logger.debug(f"Cache read in {round(elapsed_milliseconds, 2)} ms | hash : {hash} | object type : {type(cached_result)}")

                if return_cache_used_flag:
                    return cached_result, True
                else:
                    return cached_result
                
            else:
                if debug:
                    module_logger.debug(f"Cache miss | hash : {hash} | args : {args} | kwargs : {kwargs} | computing...")

                # cache miss => call function
                # NOTE: in such case we need to pass self along if it was there => pass all initial args
                result = func(*all_args, **kwargs)

                # write value to cache
                if isinstance(result, bytes):
                    _diskcache[cache_dir].set(hash, BytesIO(result), read=True)
                else:
                    _diskcache[cache_dir].set(hash, result)

                if debug:
                    module_logger.debug(f"Value saved to cache | hash : {hash} | args : {args} | object type : {type(result)}")


                if return_cache_used_flag:
                    return result, False
                else:
                    return result
            
        
        
        # create a function that allows calling my_func.clear()
        def clear():
            """
            clear the cache
            """
            global _diskcache

            if cache_dir in _diskcache:
                _diskcache[cache_dir].clear()
            
            module_logger.debug(f"disk_cache cleared | {cache_dir}")

        wrapper.clear = clear
            
        
        return wrapper
    return disk_cache_decorator